GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/Giving_Score__c.object-meta.xml
<CustomObject>
    <description>Calculates a Giving Score for the Contact, based on multiple variables</description>
    <label>Giving Score</label>
    <nameField>
        <label>Giving Score Sequence Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Giving Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoalTracker/force-app/main/default/objects/Giving_Score__c/fields/Annual_Giving_Grade__c.field-meta.xml
<CustomField>
    <fullName>Annual_Giving_Grade__c</fullName>
    <description>Captures the Grade curve of the Giving Score</description>
    <inlineHelpText>Captures the Grade curve of the Giving Score</inlineHelpText>
    <label>Annual Giving Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Annual_Giving_Score__c.field-meta.xml
<CustomField>
    <fullName>Annual_Giving_Score__c</fullName>
    <formula>(Female_Indicator__c * -0.108721482985)
+
(IF(Undergrad_Indicator__c=TRUE,1,0) * -0.352980643366)
+
(IF(Legacy_Indicator__c=TRUE,1,0) * 0.0924075344941)
+
(Events_Last_3_Years_Score__c * 0.778742556146)
+
(Volunteering_Last_3_Years_Score__c * 0.559110068155)
+
(IF(Recent_Alumni_Indicator__c=TRUE,1,0) * -0.3622758866321)
+
(IF(Dual_Affiliate_Indicator__c=TRUE,1,0)  * 0.396072360354)
+
(IF(DC__c=TRUE,1,0) * -0.776690869788)
+
(IF(CFA__c=TRUE,1,0) * -0.776442889171)
+
(IF(CIT__c=TRUE,1,0) * -0.162089946983)
+
(IF(MCS__c=TRUE,1,0) * -0.0738900731853)
+
(IF(SCS__c=TRUE,1,0) * -0.406840258543)
+
(IF(Tepper__c=TRUE,1,0) * -0.320975961036)
+
(IF(Heinz__c=TRUE,1,0) * -0.377219036522)
+
(IF(CMU__c=TRUE,1,0) * -0.583880636724)
+
(IF(Married_Flag__c=TRUE,1,0) * 0.46705153903)
+
(IF(Email_Listed_Flag__c=TRUE,1,0) * 0.849726378933)
+
(IF(Home_Phone_Listed_Flag__c=TRUE,1,0) * 0.435165415217)
+
(IF(Business_Phone_Listed_Flag__c=TRUE,1,0) * 0.3567169349)
+
(Total_Volunteer_Activities__c * -0.0321739026328)
+
(Total_Events_Attended__c * 0.194046128348)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annual Giving Score</label>
    <precision>18</precision>
    <scale>16</scale>
    <type>Number</type>
</CustomField>

GivingScoreCalc/force-app/main/default/classes/AGGrade.cls
Global class AGGrade implements Database.Batchable<sObject>{

Global FINAL List<String> AGGrades = new List<String>{'B', 'B+', 'A-', 'A', 'A+'};
Global Map<Decimal,String> gradeValuesMap = new Map<Decimal,String>();
GLobal List<Decimal> vals = new List<Decimal>();
Global Decimal max = 0;
Global Decimal min = 0;
Global Decimal range = 0;
Global Decimal bucketSize = 0;
Global Decimal boundary = 0;
Global Integer bucketCount = 0;


    global AGGrade(){
        List<Giving_Score__c> extremeMax = [SELECT Id, Annual_Giving_Score__c FROM Giving_Score__c ORDER BY Annual_Giving_Score__c DESC LIMIT 1];

        max = extremeMax[0].Annual_Giving_Score__c; 
            System.debug('extreme max score is: ' + max);

        List<Giving_Score__c> extremeMin = [SELECT Id, Annual_Giving_Score__c FROM Giving_Score__c ORDER BY Annual_Giving_Score__c ASC LIMIT 1];

        min = extremeMin[0].Annual_Giving_Score__c;        
            System.debug('extreme min score is: ' + min);
        range = max - min;
            System.debug('range is: '+ range);
        bucketSize = range / AGGrades.size();
            System.debug('bucketsize is: ' + bucketSize);


        List<Giving_Score__c> truMax = [SELECT Id, Annual_Giving_Score__c FROM Giving_Score__c ORDER BY Annual_Giving_Score__c DESC LIMIT 1000];
        Integer maxIndex = 0;
        for (Giving_Score__c gsMax : truMax){
            maxIndex ++;
            if (  (gsMax.Annual_Giving_Score__c - truMax[maxIndex].Annual_Giving_Score__c)  <  bucketSize ) {
                max = gsMax.Annual_Giving_Score__c;
                break;
            } 
        }
          System.debug('NEW max after the loop is: ' + max);
        
        List<Giving_Score__c> truMin = [SELECT Id, Annual_Giving_Score__c FROM Giving_Score__c ORDER BY Annual_Giving_Score__c ASC LIMIT 1000];
        Integer minIndex = 0;
        for (Giving_Score__c gsMin : truMin){
            minIndex ++;
            if ( (gsMin.Annual_Giving_Score__c - truMin[minIndex].Annual_Giving_Score__c)  <  (bucketSize/2)  ) {
                min = gsMin.Annual_Giving_Score__c;
                break;
            } 
        }
          System.debug('NEW min after the loop is: ' + min);

        boundary = min;
          System.debug('boundary is: ' + boundary);


        //refigure final Range and final Bucketsize after outliers are removed
        range = max - min;
        System.debug('NEW range is: '+ range);
        bucketSize = range / AGGrades.size();
        System.debug('NEW bucketsize is: ' + bucketSize);



        for(String grade : AGGrades){          
            gradeValuesMap.put(boundary, AGGrades[bucketCount]);
            boundary = boundary + bucketsize;
            bucketCount ++;
        }
          System.debug('gradeValuesMap is: ' + gradeValuesMap);
          System.debug('gradevaluesmap keyset: ' + gradeValuesMap.keyset());
        vals.addAll(gradeValuesMap.keyset());
        vals.sort();
          System.debug('sorted vals are: ' + vals);
    }







    global Database.QueryLocator start(Database.BatchableContext bc) { 
        return Database.getQueryLocator('SELECT Id, Annual_Giving_Score__c, Annual_Giving_Grade__c FROM Giving_Score__c'); 
    }  






    global void execute(Database.BatchableContext bc, List<Giving_Score__c> scope){

        for(Giving_Score__c gs : scope){
            if(vals.size() >= 2){
                for(Integer i=0; i<vals.size()-1; i++){
                    if( gs.Annual_Giving_Score__c >= vals[i] && gs.Annual_Giving_Score__c < vals[i+1] )  {
                        gs.Annual_Giving_Grade__c = gradeValuesMap.values()[i];
                    }
                    else if (gs.Annual_Giving_Score__c  < vals[0]){
                        gs.Annual_Giving_Grade__c = gradeValuesMap.values()[0];
                    }
                    else if( gs.Annual_Giving_Score__c >= vals[vals.size()-1] ) {
                        gs.Annual_Giving_Grade__c = gradeValuesMap.values()[vals.size()-1];
                    }                   
                }
            }
        }
        update scope;
    }





    global void finish(Database.BatchableContext bc){
    VGrade vg = new VGrade();
    Id batchId = Database.executeBatch(vg);
    }
}