GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/Giving_Score__c.object-meta.xml
<CustomObject>
    <description>Calculates a Giving Score for the Contact, based on multiple variables</description>
    <label>Giving Score</label>
    <nameField>
        <label>Giving Score Sequence Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Giving Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoalTracker/force-app/main/default/objects/Giving_Score__c/fields/Annual_Giving_Grade__c.field-meta.xml
<CustomField>
    <fullName>Annual_Giving_Grade__c</fullName>
    <description>Captures the Grade curve of the Giving Score</description>
    <inlineHelpText>Captures the Grade curve of the Giving Score</inlineHelpText>
    <label>Annual Giving Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Giving Scores</relationshipLabel>
    <relationshipName>Giving_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Research_Grade__c.field-meta.xml
<CustomField>
    <fullName>Research_Grade__c</fullName>
    <description>Captures the Grade curve of the Research Score</description>
    <inlineHelpText>Captures the Grade curve of the Research Score</inlineHelpText>
    <label>Research Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Volunteer_Grade__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Grade__c</fullName>
    <description>Captures the Grade curve of the Volunteer Score</description>
    <inlineHelpText>Captures the Grade curve of the Volunteer Score</inlineHelpText>
    <label>Volunteer Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/classes/GivingScoreUpdateContact.cls
Global class GivingScoreUpdateContact implements Database.Batchable<sObject>{

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Contact__c, Annual_Giving_Grade__c, Volunteer_Grade__c, Research_Grade__c FROM Giving_Score__c'); 
    }



    global void execute(Database.BatchableContext bc, List<Giving_Score__c> scope){
        List<Id> conList = new List<Id>();
        for (Giving_Score__c gs : scope){
            conList.add(gs.Contact__c);
        }

        Map<Id, Contact> conMap = new Map<Id, Contact>([SELECT Id, Giving_Score__c, Annual_Giving_Grade__c, 
                                                        Volunteer_Grade__c, Prospect_Research_Grade__c 
                                                        FROM Contact WHERE ID IN : conList]);


        for (Giving_Score__c g : scope){
            if (conMap.containsKey(g.Contact__c)){
                Contact c = conMap.get(g.Contact__c);
                c.Giving_Score__c = g.Id;
                c.Annual_Giving_Grade__c = g.Annual_Giving_Grade__c;
                c.Volunteer_Grade__c = g.Volunteer_Grade__c;
                c.Prospect_Research_Grade__c = g.Research_Grade__c;
            }
        }
    Database.update(conMap.values(), false);
    }



    global void finish(Database.BatchableContext bc){
    }
}