GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/Giving_Score__c.object-meta.xml
<CustomObject>
    <description>Calculates a Giving Score for the Contact, based on multiple variables</description>
    <label>Giving Score</label>
    <nameField>
        <label>Giving Score Sequence Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Giving Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Volunteer_Grade__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Grade__c</fullName>
    <description>Captures the Grade curve of the Volunteer Score</description>
    <inlineHelpText>Captures the Grade curve of the Volunteer Score</inlineHelpText>
    <label>Volunteer Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Volunteer_Score__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Score__c</fullName>
    <formula>(Female_Indicator__c * 0.189384987826)
+
(IF(Undergrad_Indicator__c=TRUE,1,0) * 0.80368858654) 
+
(Events_Last_3_Years_Score__c * 1.36584996219)
+
(Giver_Last_3_Years_Score__c * -0.373591917274)
+
(RFM_Score__c * 0.0532185882037)
+
(Consecutive_Years_of_Giving__c * -0.0212127698466)
+
(IF(Recent_Alumni_Indicator__c=TRUE,1,0) * 1.19204594512)
+
(IF(Dual_Affiliate_Indicator__c=TRUE,1,0) * -0.0532467316046)
+
(IF(DC__c=TRUE,1,0) * -0.592004353637)
+
(IF(CFA__c=TRUE,1,0) * -1.30009580169)
+
(IF(CIT__c=TRUE,1,0) * -0.552612370634)
+
(IF(MCS__c=TRUE,1,0) * -0.483672943228)
+
(IF(SCS__c=TRUE,1,0) * -1.4178188914)
+
(IF(Tepper__c=TRUE,1,0) * -0.327911520701)
+
(IF(Heinz__c=TRUE,1,0) * 3.26063755034)
+
(IF(CMU__c=TRUE,1,0) * 0.740071140285)
+ 
(IF(Married_Flag__c=TRUE,1,0) * 0.4879072688716)
+
(IF(Email_Listed_Flag__c=TRUE,1,0) * 1.44689572807)
+
(IF(Home_Phone_Listed_Flag__c=TRUE,1,0) * -0.405441309619)
+
(IF(Business_Phone_Listed_Flag__c=TRUE,1,0) * 0.186415239575)
+
(Current_Year_Giver_Score__c  * 0.275669214462)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volunteer Score</label>
    <precision>18</precision>
    <scale>16</scale>
    <type>Number</type>
</CustomField>

GivingScoreCalc/force-app/main/default/classes/VGrade.cls
Global class VGrade implements Database.Batchable<sObject>{

Global FINAL List<String> VGrades = new List<String>{'B', 'B+', 'A-', 'A', 'A+'};
Global Map<Decimal,String> gradeValuesMap = new Map<Decimal,String>();
GLobal List<Decimal> vals = new List<Decimal>();
Global Decimal max = 0;
Global Decimal min = 0;
Global Decimal range = 0;
Global Decimal bucketSize = 0;
Global Decimal boundary = 0;
Global Integer bucketCount = 0;


    global VGrade(){
        List<Giving_Score__c> extremeMax = [SELECT Id, Volunteer_Score__c FROM Giving_Score__c ORDER BY Volunteer_Score__c DESC LIMIT 1];

        max = extremeMax[0].Volunteer_Score__c; 
            System.debug('extreme max score is: ' + max);

        List<Giving_Score__c> extremeMin = [SELECT Id, Volunteer_Score__c FROM Giving_Score__c ORDER BY Volunteer_Score__c ASC LIMIT 1];

        min = extremeMin[0].Volunteer_Score__c;        
            System.debug('extreme min score is: ' + min);
        range = max - min;
            System.debug('range is: '+ range);
        bucketSize = range / VGrades.size();
            System.debug('bucketsize is: ' + bucketSize);


        List<Giving_Score__c> truMax = [SELECT Id, Volunteer_Score__c FROM Giving_Score__c ORDER BY Volunteer_Score__c DESC LIMIT 1000];
        Integer maxIndex = 0;
        for (Giving_Score__c gsMax : truMax){
            maxIndex ++;
            if (  (gsMax.Volunteer_Score__c - truMax[maxIndex].Volunteer_Score__c)  <  bucketSize ) {
                max = gsMax.Volunteer_Score__c;
                break;
            } 
        }
            System.debug('NEW max after the loop is: ' + max);
        
        List<Giving_Score__c> truMin = [SELECT Id, Volunteer_Score__c FROM Giving_Score__c ORDER BY Volunteer_Score__c ASC LIMIT 1000];
        Integer minIndex = 0;
        for (Giving_Score__c gsMin : truMin){
            minIndex ++;
            if ( (gsMin.Volunteer_Score__c - truMin[minIndex].Volunteer_Score__c)  <  bucketSize  ) {
                min = gsMin.Volunteer_Score__c;
                break;
            } 
        }
            System.debug('NEW min after the loop is: ' + min);

        boundary = min;
            System.debug('boundary is: ' + boundary);


        //refigure final Range and final Bucketsize after outliers are removed
        range = max - min;
        System.debug('NEW range is: '+ range);
        bucketSize = range / VGrades.size();
        System.debug('NEW bucketsize is: ' + bucketSize);



        for(String grade : VGrades){          
            gradeValuesMap.put(boundary, VGrades[bucketCount]);
            boundary = boundary + bucketsize;
            bucketCount ++;
        }
            System.debug('gradeValuesMap is: ' + gradeValuesMap);
            System.debug('gradevaluesmap keyset: ' + gradeValuesMap.keyset());
        vals.addAll(gradeValuesMap.keyset());
        vals.sort();
            System.debug('sorted vals are: ' + vals);
    }







    global Database.QueryLocator start(Database.BatchableContext bc) { 
        return Database.getQueryLocator('SELECT Id, Volunteer_Score__c, Volunteer_Grade__c FROM Giving_Score__c'); 
    }  






    global void execute(Database.BatchableContext bc, List<Giving_Score__c> scope){

        for(Giving_Score__c gs : scope){
            if(vals.size() >= 2){
                for(Integer i=0; i<vals.size()-1; i++){
                    if( gs.Volunteer_Score__c >= vals[i] && gs.Volunteer_Score__c < vals[i+1] )  {
                        gs.Volunteer_Grade__c = gradeValuesMap.values()[i];
                    }
                    else if (gs.Volunteer_Score__c  < vals[0]){
                        gs.Volunteer_Grade__c = gradeValuesMap.values()[0];
                    }
                    else if( gs.Volunteer_Score__c >= vals[vals.size()-1] ) {
                        gs.Volunteer_Grade__c = gradeValuesMap.values()[vals.size()-1];
                    }                   
                }
            }
        }
        update scope;
    }





    global void finish(Database.BatchableContext bc){
    PRGrade prg = new PRGrade();
    Id batchId = Database.executeBatch(prg);
    }
}