GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/Giving_Score__c.object-meta.xml
<CustomObject>
    <description>Calculates a Giving Score for the Contact, based on multiple variables</description>
    <label>Giving Score</label>
    <nameField>
        <label>Giving Score Sequence Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Giving Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoalTracker/force-app/main/default/objects/Giving_Score__c/fields/Annual_Giving_Grade__c.field-meta.xml
<CustomField>
    <fullName>Annual_Giving_Grade__c</fullName>
    <description>Captures the Grade curve of the Giving Score</description>
    <inlineHelpText>Captures the Grade curve of the Giving Score</inlineHelpText>
    <label>Annual Giving Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Annual_Giving_Score__c.field-meta.xml
<CustomField>
    <fullName>Annual_Giving_Score__c</fullName>
    <formula>(Female_Indicator__c * -0.108721482985)
+
(IF(Undergrad_Indicator__c=TRUE,1,0) * -0.352980643366)
+
(IF(Legacy_Indicator__c=TRUE,1,0) * 0.0924075344941)
+
(Events_Last_3_Years_Score__c * 0.778742556146)
+
(Volunteering_Last_3_Years_Score__c * 0.559110068155)
+
(IF(Recent_Alumni_Indicator__c=TRUE,1,0) * -0.3622758866321)
+
(IF(Dual_Affiliate_Indicator__c=TRUE,1,0)  * 0.396072360354)
+
(IF(DC__c=TRUE,1,0) * -0.776690869788)
+
(IF(CFA__c=TRUE,1,0) * -0.776442889171)
+
(IF(CIT__c=TRUE,1,0) * -0.162089946983)
+
(IF(MCS__c=TRUE,1,0) * -0.0738900731853)
+
(IF(SCS__c=TRUE,1,0) * -0.406840258543)
+
(IF(Tepper__c=TRUE,1,0) * -0.320975961036)
+
(IF(Heinz__c=TRUE,1,0) * -0.377219036522)
+
(IF(CMU__c=TRUE,1,0) * -0.583880636724)
+
(IF(Married_Flag__c=TRUE,1,0) * 0.46705153903)
+
(IF(Email_Listed_Flag__c=TRUE,1,0) * 0.849726378933)
+
(IF(Home_Phone_Listed_Flag__c=TRUE,1,0) * 0.435165415217)
+
(IF(Business_Phone_Listed_Flag__c=TRUE,1,0) * 0.3567169349)
+
(Total_Volunteer_Activities__c * -0.0321739026328)
+
(Total_Events_Attended__c * 0.194046128348)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annual Giving Score</label>
    <precision>18</precision>
    <scale>16</scale>
    <type>Number</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Volunteer_Grade__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Grade__c</fullName>
    <description>Captures the Grade curve of the Volunteer Score</description>
    <inlineHelpText>Captures the Grade curve of the Volunteer Score</inlineHelpText>
    <label>Volunteer Grade</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

GivingScoreCalc/force-app/main/default/objects/Giving_Score__c/fields/Volunteer_Score__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Score__c</fullName>
    <formula>(Female_Indicator__c * 0.189384987826)
+
(IF(Undergrad_Indicator__c=TRUE,1,0) * 0.80368858654) 
+
(Events_Last_3_Years_Score__c * 1.36584996219)
+
(Giver_Last_3_Years_Score__c * -0.373591917274)
+
(RFM_Score__c * 0.0532185882037)
+
(Consecutive_Years_of_Giving__c * -0.0212127698466)
+
(IF(Recent_Alumni_Indicator__c=TRUE,1,0) * 1.19204594512)
+
(IF(Dual_Affiliate_Indicator__c=TRUE,1,0) * -0.0532467316046)
+
(IF(DC__c=TRUE,1,0) * -0.592004353637)
+
(IF(CFA__c=TRUE,1,0) * -1.30009580169)
+
(IF(CIT__c=TRUE,1,0) * -0.552612370634)
+
(IF(MCS__c=TRUE,1,0) * -0.483672943228)
+
(IF(SCS__c=TRUE,1,0) * -1.4178188914)
+
(IF(Tepper__c=TRUE,1,0) * -0.327911520701)
+
(IF(Heinz__c=TRUE,1,0) * 3.26063755034)
+
(IF(CMU__c=TRUE,1,0) * 0.740071140285)
+ 
(IF(Married_Flag__c=TRUE,1,0) * 0.4879072688716)
+
(IF(Email_Listed_Flag__c=TRUE,1,0) * 1.44689572807)
+
(IF(Home_Phone_Listed_Flag__c=TRUE,1,0) * -0.405441309619)
+
(IF(Business_Phone_Listed_Flag__c=TRUE,1,0) * 0.186415239575)
+
(Current_Year_Giver_Score__c  * 0.275669214462)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Volunteer Score</label>
    <precision>18</precision>
    <scale>16</scale>
    <type>Number</type>
</CustomField>

GivingScoreCalc/force-app/main/default/classes/AGScoreDistribution2.cls
Global class AGScoreDistribution2 implements Database.Batchable<sObject>, Database.Stateful{

    Global FINAL List<String> AGgrades = new List<String>{'B', 'B+', 'A-', 'A', 'A+'};
    Global List<Giving_Score__c> gsList = new List<Giving_Score__c>();
    Global List<Giving_Score__c> agsLeftovers = new List<Giving_Score__c>();
    Global Integer counter;
    
        
        global Database.QueryLocator start(Database.BatchableContext bc) {
            return Database.getQueryLocator('SELECT Id, Annual_Giving_Score__c, Annual_Giving_Grade__c, Volunteer_Score__c, Volunteer_Grade__c FROM Giving_Score__c ORDER BY Annual_Giving_Score__c ASC, Volunteer_Score__c ASC'); 
        } 

        
        /*
        global void execute(System.QueueableContext qc){
            start(Database.BatchableContext);
        }
        */
        
        global void execute(Database.BatchableContext bc, List<Giving_Score__c> scope){
            this.gsList = scope;
               System.debug('Started AGScoreDistribution with this many Giving Scores: ' + gsList.size());
               System.debug('Started AGScoreDistribution with these Giving Scores: ' + gsList);
            Integer numberInAgsBucket = (gsList.size() / agGrades.size());        
            Integer agsRemainder = Math.mod(gsList.size(), agGrades.size());
               System.debug('agsRemainder has this many remainders: ' + agsRemainder);
    
            For(Integer i=0; i<agsRemainder; i++){
                agsLeftovers.add(gsList[i]); 
                gsList.remove(i);          
            }
            
            counter = 0;
            for(String grade : AGgrades) {            
                for(Integer i=0; i<(numberInAgsBucket); i++){                       
                    gsList[counter].Annual_Giving_Grade__c = grade;            
                    counter ++;
                }
            }
            
            for(Giving_Score__c gsc : AGSLeftovers){
                gsc.Annual_Giving_Grade__c = AGgrades[0];
                gsList.add(gsc);
                counter ++;
            }      
            update gsList;          
        }
        
    
        global void finish(Database.BatchableContext bc){
        System.debug('Giving Scores updates with new Annual Giving Grades: ' + counter);
        //VScoreDistribution vsd = new VScoreDistribution();
        //Id batchId = Database.executeBatch(vsd);
        }  
    }