Mindera/LIMSCallout/force-app/main/default/objects/Integration_Message__c/Integration_Message__c.object-meta.xml
<CustomObject>
    <label>Integration Message</label>
    <nameField>
        <label>Integration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Mindera/LIMSCallout/force-app/main/default/objects/Integration_Message__c/fields/Package__c.field-meta.xml
<CustomField>
    <fullName>Package__c</fullName>
    <label>Package</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/classes/LIMSOrderPackage.cls
@RestResource(urlMapping='/LimsAPI/*')
global class LIMSOrderPackage{
    
    @HttpPost
    global static void handlePost(){
        
        
        RestRequest request = RestContext.request;
        map<String,Object> head = request.headers;
        system.debug('requestBody--->'+request.requestBody.toString());
        map<String,Object> params = (map<String,Object>)JSON.deserializeUntyped(request.requestBody.toString());
        system.debug('params---->'+params);
        Integration_Message__c IntegrationMessage = new Integration_Message__c(Package__c=request.requestBody.toString());
        
        insert IntegrationMessage;
        
    }
     
}