Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Contact/fields/NPI_Number__c.field-meta.xml
<CustomField>
    <fullName>NPI_Number__c</fullName>
    <externalId>true</externalId>
    <label>NPI Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Requisition</label>
    <nameField>
        <label>Requisition Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Order_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Completed_Date__c</fullName>
    <label>Date of Reporting</label>
    <type>Date</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Order_Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Entry_Date__c</fullName>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Order__c/fields/Primary_Payor_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Payor_Name__c</fullName>
    <label>Primary Payor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Primary_Payor_Payor_ID__c.field-meta.xml
<CustomField>
    <fullName>Primary_Payor_Payor_ID__c</fullName>
    <label>Primary Payor: Payor ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Order__c/fields/Primary_Payor_Type__c.field-meta.xml
<CustomField>
    <fullName>Primary_Payor_Type__c</fullName>
    <label>Primary Payor Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Secondary_Payor_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Payor_Name__c</fullName>
    <label>Secondary Payor Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Secondary_Payor_Payor_ID__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Payor_Payor_ID__c</fullName>
    <label>Secondary Payor: Payor ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Mindera/LIMSCallout/force-app/main/default/objects/Order__c/fields/Secondary_Payor_Type__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Payor_Type__c</fullName>
    <label>Secondary Payor Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/classes/LIMSOrder.cls
@RestResource(urlMapping = '/LIMSOrder/*')
global with sharing class LIMSOrder {

    @HTTPPost
    global static Order__c createNewOrder(String orderStatus, Date orderEntryDate, String clientId, String physicianNpi, String accountId, String orderNumber, String primaryPayor, String primaryPayorType, String primaryPayorID, String secondaryPayor, String secondaryPayorType, String secondaryPayorID, Date orderCompletedDate){
    
    Order__c order = new Order__c();
    order.Order_Status__c = orderStatus;
    order.Order_Entry_Date__c = orderEntryDate;
    order.Name = orderNumber;
    order.Primary_Payor_Name__c = primaryPayor;
    order.Primary_Payor_Type__c = primaryPayorType;
    order.Primary_Payor_Payor_ID__c = primaryPayorID;
    order.Secondary_Payor_Name__c = secondaryPayor;
    order.Secondary_Payor_Type__c = secondaryPayorType;
    order.Secondary_Payor_Payor_ID__c = secondaryPayorID;
    order.Order_Completed_Date__c = orderCompletedDate;
    
    //(not needed - resides on related account/client) order.Practice_Id__c = clientId;
    order.Account__c = accountId;
    
    //get contact/physician from NPI
    Id contactRef = [Select Id from Contact where NPI_Number__c = :physicianNpi].Id;
    
    //insert contact/physician
    order.Contact__c = contactRef;
    
    List<Order__c> orderCheck = [Select Id from Order__c where Name = :orderNumber];
    
    if (orderCheck.size() > 0) {
        Order__c o = orderCheck.get(0);
        order.Id = o.id;
        update order;
        }
    else{
    insert order;
    }
    
    return order;
    
   }
}