Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Contact/fields/NPI_Number__c.field-meta.xml
<CustomField>
    <fullName>NPI_Number__c</fullName>
    <externalId>true</externalId>
    <label>NPI Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Mindera/MinderaPromotionWtuhApexClasses/force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Requisition</label>
    <nameField>
        <label>Requisition Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Mindera/LIMSCallout/force-app/main/default/classes/LIMSOrder_TC.cls
@isTest
public class LIMSOrder_TC {
    @istest public static void testLimorder(){
       Account Acc=new Account();
        Acc.Name='Test';
        Acc.BillingCity='New York';
        Insert Acc;
        
        Contact cntrec=new Contact();
        cntrec.AccountId=Acc.id;
        cntrec.Email='test@gmail.com';
        cntrec.FirstName='testcontact';
        cntrec.LastName='last';
        cntrec.NPI_Number__c='1234556789';
        insert cntrec;
        
        LIMSOrder.createNewOrder('In Process', Date.today().adddays(3), 'test','1234556789' , Acc.id,'687946', 'testpayor1','testertype', 'test456','testpayor 3', 'testtype2','test658',Date.today().adddays(10));
    }
    @istest public static void testlimexistorder(){
        Account Acc=new Account();
        Acc.Name='Test';
        Acc.BillingCity='New York';
        Insert Acc;
        
        Contact cntrec=new Contact();
        cntrec.AccountId=Acc.id;
        cntrec.Email='test@gmail.com';
        cntrec.FirstName='testcontact';
        cntrec.LastName='last';
        cntrec.NPI_Number__c='1234556789';
        insert cntrec;
        
        Order__c order = new Order__c();
        order.Name='687946';
        insert order;
        
        LIMSOrder.createNewOrder('In Process', Date.today().adddays(3), 'test','1234556789' , Acc.id,'687946', 'testpayor1','testertype', 'test456','testpayor 3', 'testtype2','test658',Date.today().adddays(10));
    }
}