GoalTracker/force-app/main/default/objects/Goal_Tracker__c/Goal_Tracker__c.object-meta.xml
<CustomObject>
    <description>Tracks Prospect Manager Goals and Attainment</description>
    <label>Goal Tracker</label>
    <nameField>
        <displayFormat>GT-{00000}</displayFormat>
        <label>Goal Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goal Trackers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

GoalTracker/force-app/main/default/objects/Goal_Tracker__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>Enter the fiscal year for this user&apos;s goals</description>
    <inlineHelpText>Enter the fiscal year for this user&apos;s goals</inlineHelpText>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Goal_Tracker__c/fields/Last_Goals_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Goals_Update__c</fullName>
    <description>Date and Time of the last update on this goals record</description>
    <inlineHelpText>Date and Time of the last update on this goals record</inlineHelpText>
    <label>Last Goals Update</label>
    <type>DateTime</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Goal_Tracker__c/fields/Prospect_Manager__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect Manager</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>IP Prospect Manager, Planned Giving Prospect Manager, UA Prospect Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Goal_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Goal_Tracker__c/fields/Qualifications__c.field-meta.xml
<CustomField>
    <fullName>Qualifications__c</fullName>
    <label>Qualifications</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Goal_Tracker__c/fields/Qualifications_Count__c.field-meta.xml
<CustomField>
    <fullName>Qualifications_Count__c</fullName>
    <label>Qualifications Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Goal_Tracker__c/fields/Qualifications_Goal__c.field-meta.xml
<CustomField>
    <fullName>Qualifications_Goal__c</fullName>
    <label>Qualifications Goal</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/Prospect_Rating__c.object-meta.xml
<CustomObject>
    <description>AQ_Custom</description>
    <label>Prospect Rating</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Prospect Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prospect Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>AQ_Custom (BP)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Prospect Ratings</relationshipLabel>
    <relationshipName>Prospect_Ratings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>AQ_Custom(BP)</description>
    <formula>IF ( ISBLANK ( Start_Date__c) 
, IF ( ISBLANK ( End_Date__c)
, TRUE
, IF ( End_Date__c&gt; TODAY(), TRUE, FALSE) 
)
, IF ( Start_Date__c &lt;= TODAY()
, IF (ISBLANK ( End_Date__c)
, TRUE
, IF (End_Date__c &gt; TODAY(), TRUE, FALSE))
, FALSE
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <formula>IF( (MONTH(Start_Date__c ) &gt;= 7 &amp;&amp; MONTH(Start_Date__c ) &lt;= 12),
TEXT(YEAR(Start_Date__c)+1), TEXT(YEAR(Start_Date__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fiscal Year</label>
    <type>Text</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Goal_Fiscal__c.field-meta.xml
<CustomField>
    <fullName>Goal_Fiscal__c</fullName>
    <description>Hidden field for temporarily passing the Fiscal year of the Goal</description>
    <inlineHelpText>Hidden field for temporarily passing the Fiscal year of the Goal</inlineHelpText>
    <label>Goal Fiscal</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Goal_Link__c.field-meta.xml
<CustomField>
    <fullName>Goal_Link__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+ Id,  Account__r.Account_Name_Link__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Goal Link</label>
    <type>Text</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Qualification_Credit__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Credit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>AQ_Custom</description>
    <inlineHelpText>Look up field to select who is the user to receive credit.</inlineHelpText>
    <label>Qualification Credit</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prospect_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>AQ_Custom(BP)</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

GoalTracker/force-app/main/default/objects/Prospect_Rating__c/recordTypes/Qualification.recordType-meta.xml
<RecordType>
    <fullName>Qualification</fullName>
    <active>true</active>
    <description>This is created when a prospect has been qualified.</description>
    <label>Qualification</label>
</RecordType>

GoalTracker/force-app/main/default/classes/GoalTracker_QualificationsUtility.cls
public class GoalTracker_QualificationsUtility {

public static Set<Id> users = new Set<ID>();
public static Set<String> fiscalYears = new Set<String>();
public static List<Goal_Tracker__c> goals = new List<Goal_Tracker__c>();
public static String currentFiscalYear = [SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year' AND StartDate <= TODAY AND EndDate >= TODAY].FiscalYearSettings.Name;

    @InvocableMethod
    public static void doWhat(List<Prospect_Rating__c> quals){
          //make a set of Users and a set of Fiscal Yrs to query with
        for(Prospect_Rating__c pr : quals){
            users.add(pr.Qualification_Credit__c); 
            if(pr.Fiscal_Year__c != NULL){
            	fiscalYears.add(pr.Fiscal_Year__c);
            }
            if(pr.Goal_Fiscal__c != NULL){
            	fiscalYears.add(pr.Goal_Fiscal__c);
            }
        }
        
        
        
          System.debug('set of users has: ' + users);
          System.debug('set of fiscalYears has: ' + fiscalYears);        
        
        
          // query for a list of goalTrackers associated with the users and FY's above
        goals = [SELECT Id, Prospect_Manager__c, Fiscal_Year__c, Qualifications_Goal__c,  
                 Qualifications_Count__c, Qualifications__c, Last_Goals_Update__c 
                 FROM Goal_Tracker__c
                 WHERE fiscal_Year__c IN : fiscalYears
                 AND Prospect_Manager__c IN : users];
        
          System.debug('results set of goals has: ' + goals.size() + ' elements'); 
          System.debug('results set of goals has: ' + goals);

          // query for the all users' qualification prospect ratings (active and from all the named FY's)
        List<Prospect_Rating__c> prList = [SELECT Id, Account__c, Qualification_Credit__c, Name, 
                                           Account__r.Account_Name_Link__c, Goal_Link__c, Fiscal_Year__c
                                           FROM Prospect_Rating__c
                                           WHERE RecordType.Name = 'Qualification'
                                           AND Active__c = TRUE
                                           AND Fiscal_Year__c IN : fiscalYears
                                           AND Qualification_Credit__c IN : users
                                           ORDER BY Start_Date__c DESC];
        System.debug('prList query had: ' + prList.size() + ' elements');  
        System.debug('prList query had: ' + prList);

        for (ID u : users){
            Map<String, Goal_Tracker__c> goalsByFiscalMap = new Map<String, Goal_Tracker__c>();
            
            for(Goal_Tracker__c gt : goals) {
                if (u == gt.Prospect_Manager__c) {
                    gt.Qualifications_Count__c = 0;
                    gt.Qualifications__c = '';
                    goalsByFiscalMap.put(gt.Fiscal_Year__c, gt);        
                }
            }
            
            for(Prospect_Rating__c pr : prList){
                if(u == pr.Qualification_Credit__c){
                    if(goalsByFiscalMap.containsKey(pr.Fiscal_Year__c)){    
                        Goal_Tracker__c thisGoal = goalsByFiscalMap.get(pr.Fiscal_Year__c);
                        thisGoal.Qualifications_Count__c = thisGoal.Qualifications_Count__c + 1;
                        thisGoal.Qualifications__c = thisGoal.Qualifications__c + pr.Account__r.Account_Name_Link__c + '<br>';
                        thisGoal.Last_Goals_Update__c = System.Now();
                    }

                }  
            }
        }
        for (Goal_Tracker__c g : goals){
        	if (g.Qualifications_Count__c > 20) {
            	g.Qualifications__c = 'See Report';            
            }    
        }
        update goals;
    }    
}